### ISSUE TITLE
release date planned?

### ISSUE THREAD

**Issue by thibautjombart** [Mikata-Project/ggthemr#36]
Hi there, 

Thanks for developing a cool package! :) 
 
It is used in production as part of the data analytics pipeline for the response to Ebola in North Kivu, DRC. So far we put *ggthemr* on our [deployer](https://github.com/reconhub/deployer) but it'd be nice to know if / when a CRAN release is to be expected. Any rough ETA?

**Comment by amy17519** [comment]
@thibautjombart We plan to submit to CRAN soon. Hopefully it can be available by 2021.

FYI, @cttobin recently transferred the repo to @Mikata-Project. Devs at Mikata will be maintaining this package onward
