### ISSUE TITLE
Add topic: ggplot2-themes

### ISSUE THREAD

**Issue by katrinleinweber** [Mikata-Project/ggthemr#37]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/ggplot2-themes](https://github.com/topics/ggplot2-themes), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by amy17519** [comment]
thanks for your suggestion! Just added the topic!
